#Requires -Version 7.0
<#
.SYNOPSIS
  Generate the static (Dataview-free) project tables in _meta/HOME.md.
.DESCRIPTION
  The core-vs-augmented editor split (spec §System architecture, layer 4):
  HOME.md must be fully useful with no plugins installed. Dataview queries are
  an optional augmentation layered on top for adopters who have Obsidian —
  this script is what keeps the vault operable without it.

  Reads every _meta/registry/*.md card (the canonical project roster) and
  writes one plain-markdown table per category into HOME.md, between
  <!-- STATIC-HOME:START --> / <!-- STATIC-HOME:END --> markers. Categories
  are discovered dynamically from whatever `category:` values are actually
  present in the registry — no fixed category list, no external manifest
  dependency. If HOME.md has no markers, nothing is written (never guesses
  at placement) and a template block is printed instead.

  Idempotent: regenerating replaces only the managed block.
.PARAMETER Root
  Vault root.
.EXAMPLE
  build-static-home.ps1 -Root .
#>
[CmdletBinding()]
param(
  [string]$Root = '.'
)

$ErrorActionPreference = 'Stop'
function Say { param([string]$m) Write-Host $m }

$START = '<!-- STATIC-HOME:START -->'
$END   = '<!-- STATIC-HOME:END -->'

$regDir = Join-Path $Root '_meta/registry'
if (-not (Test-Path $regDir)) { throw "registry not found: $regDir" }

$cards = @()
foreach ($f in (Get-ChildItem $regDir -Filter '*.md' -File | Sort-Object Name)) {
  $fmMatch = [regex]::Match((Get-Content $f.FullName -Raw -Encoding UTF8), '(?s)\A---\s*\r?\n(.*?)\r?\n---')
  if (-not $fmMatch.Success) { Say "WARN no frontmatter, skipped: $($f.Name)"; continue }
  $fm = @{}
  foreach ($line in ($fmMatch.Groups[1].Value -split "`r?`n")) {
    if ($line -match '^([\w_]+):\s*(.*)$') { $fm[$Matches[1]] = $Matches[2].Trim() }
  }
  if (-not $fm['category']) { continue }
  $cards += [pscustomobject]@{
    Basename    = $f.BaseName
    Category    = $fm['category']
    Title       = if ($fm['title']) { $fm['title'] } else { $f.BaseName }
    Description = $fm['description']
    Phase       = $fm['phase']
    Risk        = $fm['risk']
    Repo        = $fm['repo']
    Url         = $fm['url']
  }
}
$catCount = (@($cards.Category | Sort-Object -Unique)).Count
Say ("parsed {0} registry card(s) across {1} categor{2}" -f $cards.Count, $catCount, $(if ($catCount -eq 1) { 'y' } else { 'ies' }))

function Format-Cell { param($v) if ($v) { ($v -replace '\|','\|') } else { '—' } }

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine($START)
[void]$sb.AppendLine()
[void]$sb.AppendLine('_Static project index — generated by build-static-home.ps1 from `_meta/registry/`. Requires no plugin; regenerate any time the registry changes._')
[void]$sb.AppendLine()
foreach ($cat in ($cards.Category | Sort-Object -Unique)) {
  [void]$sb.AppendLine("## $cat")
  [void]$sb.AppendLine()
  [void]$sb.AppendLine('| Project | Description | Phase | Risk | Repo | Live |')
  [void]$sb.AppendLine('|---|---|---|---|---|---|')
  foreach ($c in ($cards | Where-Object { $_.Category -eq $cat } | Sort-Object Title)) {
    $repo = if ($c.Repo) { "[GitHub]($($c.Repo))" } else { '—' }
    $live = if ($c.Url)  { "[↗]($($c.Url))" } else { '—' }
    [void]$sb.AppendLine("| [[$($c.Basename)`|$(Format-Cell $c.Title)]] | $(Format-Cell $c.Description) | $(Format-Cell $c.Phase) | $(Format-Cell $c.Risk) | $repo | $live |")
  }
  [void]$sb.AppendLine()
}
[void]$sb.Append($END)
$block = $sb.ToString()

$homeFile = Join-Path $Root '_meta/HOME.md'
if (-not (Test-Path $homeFile)) {
  Say "no _meta/HOME.md found — printing the block instead of writing:"
  Write-Output $block
  exit 0
}

$original = Get-Content -Path $homeFile -Raw -Encoding UTF8
$pattern = [regex]::Escape($START) + '.*?' + [regex]::Escape($END)
$reOpts = [System.Text.RegularExpressions.RegexOptions]::Singleline
# NOTE: PowerShell's -match/-notmatch operators do not honor RegexOptions.Singleline,
# so '.' would never span the newlines between marker lines — use [regex]::IsMatch
# explicitly (found via staged-vault rehearsal, 2026-07-03).
if (-not [regex]::IsMatch($original, $pattern, $reOpts)) {
  Say "HOME.md has no $START / $END markers — skipped (never guesses at placement). Insert this block manually once, then re-run:"
  Write-Output $block
  exit 0
}
# scriptblock evaluator, not a literal replacement string — table content may contain
# '$' or backreference-like sequences that a string replacement would misinterpret
$updated = [regex]::Replace($original, $pattern, { param($m) $block }, $reOpts)
[System.IO.File]::WriteAllText($homeFile, $updated, [System.Text.UTF8Encoding]::new($false))
Say "regenerated static project tables in $($homeFile.Substring($Root.Length).TrimStart('\','/'))"
